"""
Live RBAC certification tests.

These tests validate that the permissions defined in the RBAC manifests are
actually granted end-to-end on a live (or disposable) cluster.  They use
SelfSubjectAccessReview (SSAR) so they are non-mutating: no resources are
created or deleted.  The current kubeconfig user (or service account) must
already have the documented RBAC applied before these tests are run.

Gating
------
Tests are skipped unless the ``ACM_ENABLE_LIVE_RBAC_CERTIFICATION=1``
environment variable is set.  Set ``ACM_LIVE_RBAC_CONTEXT`` to target a
specific kubeconfig context; omit it to use the active context.

    ACM_ENABLE_LIVE_RBAC_CERTIFICATION=1 \\
    ACM_LIVE_RBAC_CONTEXT=my-disposable-hub \\
    pytest tests/test_rbac_live_certification.py -v -m live_rbac_certification

Cluster assumptions
-------------------
* The cluster must have the ACM RBAC manifests applied
  (``deploy/rbac/`` or via ``setup-rbac.sh``).
* The kubeconfig used must be the *service-account* kubeconfig generated by
  the bootstrap step, not a cluster-admin kubeconfig.
* For the decommission/finalization scenarios the optional decommission
  ClusterRole (``deploy/rbac/extensions/decommission/``) must also be bound.
* Tests are safe to run against any cluster; they make no writes.
"""

from __future__ import annotations

import os
from typing import Generator

import pytest

# ---------------------------------------------------------------------------
# Gate: skip the whole module unless the certification flag is set
# ---------------------------------------------------------------------------
_ENABLED = os.environ.get("ACM_ENABLE_LIVE_RBAC_CERTIFICATION", "").strip() in ("1", "true", "yes")
_SKIP_REASON = (
    "live RBAC certification tests require ACM_ENABLE_LIVE_RBAC_CERTIFICATION=1 "
    "and a cluster context with RBAC already applied"
)

pytestmark = pytest.mark.live_rbac_certification


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def live_context() -> str | None:
    """Return the Kubernetes context to use for live checks (may be None)."""
    return os.environ.get("ACM_LIVE_RBAC_CONTEXT") or None


@pytest.fixture(scope="module")
def rbac_validator(live_context):
    """Create a KubeClient + RBACValidator wired to the live context.

    Skips the test if the KubeClient cannot be initialised (e.g. the context
    does not exist or the cluster is unreachable).
    """
    if not _ENABLED:
        pytest.skip(_SKIP_REASON)

    from lib.kube_client import KubeClient
    from lib.rbac_validator import RBACValidator

    try:
        client = KubeClient(context=live_context)
        return RBACValidator(client, role="operator")
    except Exception as exc:  # noqa: BLE001
        pytest.skip(f"Could not connect to cluster context {live_context!r}: {exc}")


@pytest.fixture(scope="module")
def validator_rbac_validator(live_context):
    """RBACValidator wired to the live context for the *validator* role."""
    if not _ENABLED:
        pytest.skip(_SKIP_REASON)

    from lib.kube_client import KubeClient
    from lib.rbac_validator import RBACValidator

    try:
        client = KubeClient(context=live_context)
        return RBACValidator(client, role="validator")
    except Exception as exc:  # noqa: BLE001
        pytest.skip(f"Could not connect to cluster context {live_context!r}: {exc}")


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _check_permission(validator, api_group: str, resource: str, verb: str, namespace: str | None = None) -> None:
    """Assert a single SSAR check passes and produce a useful failure message."""
    from lib.exceptions import ValidationError

    scope = f"namespace={namespace}" if namespace else "cluster-scope"
    try:
        allowed, reason = validator.check_permission(api_group, resource, verb, namespace)
    except ValidationError as exc:
        pytest.fail(
            f"SSAR check could not be completed for "
            f"{verb} {api_group or 'core'}/{resource} ({scope}): {exc}"
        )
    assert allowed, (
        f"Permission DENIED: {verb} {api_group or 'core'}/{resource} ({scope})"
        + (f" — {reason}" if reason else "")
    )


# ---------------------------------------------------------------------------
# Scenario: standard switchover (operator role – cluster-scoped)
# ---------------------------------------------------------------------------


class TestLiveOperatorClusterPermissions:
    """Validate cluster-scoped permissions required for normal switchover."""

    def test_get_namespaces(self, rbac_validator):
        _check_permission(rbac_validator, "", "namespaces", "get")

    def test_list_nodes(self, rbac_validator):
        _check_permission(rbac_validator, "", "nodes", "list")

    def test_get_clusteroperators(self, rbac_validator):
        _check_permission(rbac_validator, "config.openshift.io", "clusteroperators", "get")

    def test_get_clusterversions(self, rbac_validator):
        _check_permission(rbac_validator, "config.openshift.io", "clusterversions", "get")

    def test_get_managedclusters(self, rbac_validator):
        _check_permission(rbac_validator, "cluster.open-cluster-management.io", "managedclusters", "get")

    def test_list_managedclusters(self, rbac_validator):
        _check_permission(rbac_validator, "cluster.open-cluster-management.io", "managedclusters", "list")

    def test_patch_managedclusters(self, rbac_validator):
        """Operator must be able to patch ManagedClusters during activation."""
        _check_permission(rbac_validator, "cluster.open-cluster-management.io", "managedclusters", "patch")

    def test_get_multiclusterhubs(self, rbac_validator):
        _check_permission(rbac_validator, "operator.open-cluster-management.io", "multiclusterhubs", "get")

    def test_get_multiclusterobservabilities(self, rbac_validator):
        _check_permission(
            rbac_validator,
            "observability.open-cluster-management.io",
            "multiclusterobservabilities",
            "get",
        )

    def test_list_multiclusterobservabilities(self, rbac_validator):
        _check_permission(
            rbac_validator,
            "observability.open-cluster-management.io",
            "multiclusterobservabilities",
            "list",
        )


# ---------------------------------------------------------------------------
# Scenario: standard switchover (operator role – hub namespace-scoped)
# ---------------------------------------------------------------------------


class TestLiveOperatorHubNamespacePermissions:
    """Validate hub namespace-scoped permissions required for normal switchover."""

    # --- open-cluster-management-backup ---

    def test_backup_ns_get_backupschedules(self, rbac_validator):
        _check_permission(
            rbac_validator,
            "cluster.open-cluster-management.io",
            "backupschedules",
            "get",
            namespace="open-cluster-management-backup",
        )

    def test_backup_ns_patch_backupschedules(self, rbac_validator):
        """Operator must be able to pause the BackupSchedule on primary prep."""
        _check_permission(
            rbac_validator,
            "cluster.open-cluster-management.io",
            "backupschedules",
            "patch",
            namespace="open-cluster-management-backup",
        )

    def test_backup_ns_create_restores(self, rbac_validator):
        """Operator must be able to create a Restore resource during activation."""
        _check_permission(
            rbac_validator,
            "cluster.open-cluster-management.io",
            "restores",
            "create",
            namespace="open-cluster-management-backup",
        )

    def test_backup_ns_get_restores(self, rbac_validator):
        _check_permission(
            rbac_validator,
            "cluster.open-cluster-management.io",
            "restores",
            "get",
            namespace="open-cluster-management-backup",
        )

    def test_backup_ns_get_velero_backups(self, rbac_validator):
        _check_permission(
            rbac_validator,
            "velero.io",
            "backups",
            "get",
            namespace="open-cluster-management-backup",
        )

    def test_backup_ns_get_bsl(self, rbac_validator):
        """Operator must be able to inspect BackupStorageLocations for health."""
        _check_permission(
            rbac_validator,
            "velero.io",
            "backupstoragelocations",
            "get",
            namespace="open-cluster-management-backup",
        )

    # --- open-cluster-management-observability ---

    def test_obs_ns_patch_deployments(self, rbac_validator):
        """Operator must be able to scale Thanos deployments during switchover."""
        _check_permission(
            rbac_validator,
            "apps",
            "deployments",
            "patch",
            namespace="open-cluster-management-observability",
        )

    def test_obs_ns_patch_statefulsets_scale(self, rbac_validator):
        """Operator must be able to scale Thanos compactor StatefulSets."""
        _check_permission(
            rbac_validator,
            "apps",
            "statefulsets/scale",
            "patch",
            namespace="open-cluster-management-observability",
        )

    def test_obs_ns_get_secrets(self, rbac_validator):
        _check_permission(
            rbac_validator,
            "",
            "secrets",
            "get",
            namespace="open-cluster-management-observability",
        )

    # --- multicluster-engine ---

    def test_mce_ns_patch_configmaps(self, rbac_validator):
        _check_permission(
            rbac_validator,
            "",
            "configmaps",
            "patch",
            namespace="multicluster-engine",
        )


# ---------------------------------------------------------------------------
# Scenario: old-hub finalization — MCO delete
# ---------------------------------------------------------------------------


class TestLiveOldHubFinalizationPermissions:
    """Validate MCO delete permission required when finalization deletes MCO on the old hub.

    This is the critical permission tracked by the issue:
    ``delete observability.open-cluster-management.io/multiclusterobservabilities``
    """

    def test_delete_multiclusterobservabilities(self, rbac_validator):
        """Operator must be able to delete the MCO CR on the old hub during finalization.

        This permission is distinct from the baseline ``get``/``list`` already covered
        by normal switchover and is required when ``old_hub_action == 'secondary'``
        and the Observability stack needs to be torn down.
        """
        _check_permission(
            rbac_validator,
            "observability.open-cluster-management.io",
            "multiclusterobservabilities",
            "delete",
        )


# ---------------------------------------------------------------------------
# Scenario: decommission
# ---------------------------------------------------------------------------


class TestLiveDecommissionPermissions:
    """Validate delete permissions required for the optional decommission flow.

    These are sourced from the opt-in decommission ClusterRole
    (``deploy/rbac/extensions/decommission/``).  Tests are skipped when the
    additional role is not bound (permission check returns False rather than
    erroring).
    """

    def test_delete_managedclusters(self, rbac_validator):
        """Decommission step must be able to delete ManagedCluster objects."""
        _check_permission(rbac_validator, "cluster.open-cluster-management.io", "managedclusters", "delete")

    def test_delete_multiclusterhubs(self, rbac_validator):
        """Decommission step must be able to delete the MultiClusterHub CR."""
        _check_permission(rbac_validator, "operator.open-cluster-management.io", "multiclusterhubs", "delete")

    def test_delete_multiclusterobservabilities_for_decommission(self, rbac_validator):
        """Decommission step must be able to delete the MCO CR."""
        _check_permission(
            rbac_validator,
            "observability.open-cluster-management.io",
            "multiclusterobservabilities",
            "delete",
        )


# ---------------------------------------------------------------------------
# Scenario: validator role (read-only)
# ---------------------------------------------------------------------------


class TestLiveValidatorClusterPermissions:
    """Validate that the validator role can read cluster-scoped resources."""

    def test_get_managedclusters(self, validator_rbac_validator):
        _check_permission(validator_rbac_validator, "cluster.open-cluster-management.io", "managedclusters", "get")

    def test_list_managedclusters(self, validator_rbac_validator):
        _check_permission(validator_rbac_validator, "cluster.open-cluster-management.io", "managedclusters", "list")

    def test_get_multiclusterhubs(self, validator_rbac_validator):
        _check_permission(validator_rbac_validator, "operator.open-cluster-management.io", "multiclusterhubs", "get")

    def test_get_clusterversions(self, validator_rbac_validator):
        _check_permission(validator_rbac_validator, "config.openshift.io", "clusterversions", "get")


# ---------------------------------------------------------------------------
# Scenario: full validate_all_permissions smoke (operator)
# ---------------------------------------------------------------------------


class TestLiveValidateAllPermissions:
    """Run the full RBACValidator.validate_all_permissions() in SSAR mode."""

    def test_all_required_permissions_pass(self, rbac_validator):
        """validate_all_permissions() must report no errors for a correctly bound operator SA."""
        all_valid, errors = rbac_validator.validate_all_permissions(
            include_decommission=False,
            skip_observability=False,
        )
        flat_errors = [msg for msgs in errors.values() for msg in msgs]
        assert all_valid, f"RBAC validation failed with {len(flat_errors)} error(s):\n" + "\n".join(flat_errors)

    def test_decommission_permissions_pass_when_bound(self, rbac_validator):
        """With decommission ClusterRole bound, validate_cluster_permissions(include_decommission=True) must pass."""
        all_valid, errors = rbac_validator.validate_cluster_permissions(
            include_decommission=True,
            skip_observability=False,
        )
        assert all_valid, f"Decommission RBAC validation failed:\n" + "\n".join(errors)
