{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ include "acm-switchover-rbac.chart" . }}
    app.kubernetes.io/name: {{ include "acm-switchover-rbac.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/part-of: acm-switchover-rbac
    app.kubernetes.io/role: common
{{- end }}
